# SERVER ENDPOINT
server:
  port: ${SERVER_PORT:7979}
  servlet:
    session:
      cookie:
        name: ${OMC_SERVER_SERVLET_SESSION_COOKIE_NAME:ORGMANAGERSESSIONID}

management:
   server:
      port: ${MANAGEMENT_PORT:7878}
   endpoints:
      web:
         base-path: /
         exposure:
            include: health,info,metrics
            

      

# public url
application:
   url: ${APPLICATION_URL:}
   
# client url if frontend deployed on another server   
client:
   url: ${CLIENT_URL:}   

# SPRING CONFIGURATION
spring:
  profiles:
    include:
      - components

# OAUTH INTEGRATION
security:
  oauth2:
    client:
      userAuthorizationUri: ${OAUTH_AUTH_URI:}
      accessTokenUri: ${OAUTH_TOKEN_URI:}
      clientId: ${OAUTH2_CLIENT_CLIENTID:}
      clientSecret: ${OAUTH2_CLIENT_CLIENTSECRET:}
      scopes: ${OAUTH_SCOPES:profile,email,user.roles.me}
    resource:
      id: ${OAUTH2_CLIENT_CLIENTID:}
      jwk:
        keySetUri: ${OMC_SECURITY_OAUTH2_JWK_URI:}

# AAC APIS
aac:
  uri: ${AAC_URI:}

# LOGGING
logging:
  level:
    ROOT: INFO
    it.smartcommunitylab.orgmanager: ${LOG_LEVEL:DEBUG}
    org.springframework.security: ${OMC_LOGGING_LEVEL_ORGSPRINGFRAMEWORKSECURITY:INFO}

# SWAGGER
swagger:
  title:
    orgmanager: Organization Management API
  description:
    orgmanager: Organization Management API
  version: 1.0.0
  license: Apache License, Version 2.0
  licenseUrl: http://www.apache.org/licenses/LICENSE-2.0
  contact:
    name:  Smart Community Lab
    url: www.smartcommunitylab.it
    email: info@smartcommunitylab.it
