# SERVER ENDPOINT
server:
  port: ${OMC_SERVER_PORT:7979}
  servlet:
    session:
      cookie:
        name: ${OMC_SERVER_SERVLET_SESSION_COOKIE_NAME:ORGMANAGERSESSIONID}

# SPRING CONFIGURATION
spring:
  datasource:
    url: ${OMC_SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/orgmanager}
    username: ${OMC_SPRING_DATASOURCE_USERNAME:postgres}
    password: ${OMC_SPRING_DATASOURCE_PASSWORD:password}
    driver-class-name: ${OMC_SPRING_DATASOURCE_DRIVERCLASSNAME:org.postgresql.Driver}
  jpa:
    database-platform: ${OMC_SPRING_JPA_DATABASEPLATFORM:org.hibernate.dialect.PostgreSQLDialect}
    generate-ddl: ${OMC_SPRING_JPA_GENERATEDDL:true}
    hibernate:
      ddl-auto: ${OMC_SPRING_JPA_HIBERNATE_DDLAUTO:update}
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: ${OMC_SPRING_JPA_PROPERTIES_HIBERNATE_JDBC_LOB_NONCONTEXTUALCREATION:true}
  profiles:
    include:
      - components

# OAUTH INTEGRATION
security:
  oauth2:
    client:
      clientId: ${OMC_SECURITY_OAUTH2_CLIENT_CLIENTID:48ccbed6-c9d7-453c-86a4-e471ca09a0e7}
      clientSecret: ${OMC_SECURITY_OAUTH2_CLIENT_CLIENTSECRET:33e7080f-e93b-4687-90b8-2887c4f507fc}
    resource:
      id: ${OMC_SECURITY_OAUTH2_CLIENT_CLIENTID:48ccbed6-c9d7-453c-86a4-e471ca09a0e7}
      jwk:
        keySetUri: ${OMC_SECURITY_OAUTH2_JWK_URI:http://localhost:8080/aac/jwk}

# AAC APIS
aac:
  uri: ${OMC_AAC_URI:http://localhost:8080/aac/}

# LOGGING
logging:
  level:
    org.springframework.security: ${OMC_LOGGING_LEVEL_ORGSPRINGFRAMEWORKSECURITY:DEBUG}

# SWAGGER
swagger:
  title:
    orgmanager: Organization Management API
  description:
    orgmanager: Organization Management API
  version: 1.0.0
  license: Apache License, Version 2.0
  licenseUrl: http://www.apache.org/licenses/LICENSE-2.0
  contact:
    name:  Smart Community Lab
    url: www.smartcommunitylab.it
    email: info@smartcommunitylab.it