# COMPONENTS DATA
componentsconfig:
  components:
    # API Manager
    - name: API Manager
      componentId: apimanager
      roles: ROLE_PUBLISHER,ROLE_SUBSCRIBER
      
    # Apache NiFi
    - name: Apache NiFi
      componentId: nifi
      roles: ROLE_MANAGER,ROLE_MONITOR
      
    # WSO2 DSS
    - name: Data Services Server
      componentId: dss
      roles: ROLE_MANAGER,ROLE_USER
            
    # Cyclotron
    - name: Cyclotron
      componentId: cyclotron
      roles: ROLE_MANAGER,ROLE_USER
      
    # Superset
#    - name: Superset
#      componentId: superset
#      roles: ROLE_MANAGER,ROLE_USER
      
    # Geoserver
    - name: Geoserver
      componentId: geoserver
      roles: ROLE_MANAGER,ROLE_USER
      
    # Grafana
    - name: Grafana
      componentId: grafana
      roles: ROLE_ADMIN,ROLE_EDITOR,ROLE_VIEWER

    # CKAN
    - name: CKAN Open Data Catalogue
      componentId: ckan
      roles: ROLE_MANAGER,ROLE_USER
      
    # Minio
    - name: Minio
      componentId: minio
      roles: ROLE_READWRITE,ROLE_READONLY
      
      
    # Resource Manager
    - name: Resource Manager
      componentId: resourcemanager
      roles: ROLE_ADMIN,ROLE_USER,ROLE_RESOURCE_ADMIN,ROLE_CONSUMER_ADMIN

      
    # Nuclio
    - name: Nuclio
      componentId: nuclio
      roles: ROLE_OPERATOR,ROLE_DEVELOPER     
